<?php

namespace app\modules\admin\models;

use Yii;
use yii\web\UploadedFile;

class Product_admin extends \yii\db\ActiveRecord
{
    public $file;

    public static function tableName()
    {
        return 'product';
    }

    public function getCategory_admin()
    {
        return $this->hasOne(Category_admin::class, ['id' => 'category_id']);
    }

    public function rules()
    {
        return [
            [['category_id', 'title', 'content'], 'required'],
            [['category_id', 'is_offer'], 'integer'],
            [['content'], 'string'],
            [['price', 'old_price'], 'number'],
            [['price', 'old_price'], 'default', 'value' => 0],
            [['img'], 'default', 'value' => 'products/no-image.png'],
            [['title', 'description', 'keywords', 'img'], 'string', 'max' => 255],
            [['file'], 'image'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_id' => 'Категория',
            'title' => 'Наименование',
            'content' => 'Описание товара',
            'price' => 'Цена',
            'old_price' => 'Старая цена',
            'description' => 'Заметки админа',
            'keywords' => 'Ключевое клово',
            'img' => 'Картинка',
            'file' => 'Картинка',
            'is_offer' => 'Горячий товар',
        ];
    }

    public function beforeSave($insert)
    {
        if($file = UploadedFile::getInstance($this, 'file')){//берем информацию о загружаемом файле
            $dir = 'products/' . date("Y-m-d") . '/';//указываем путь к папке где будут сохраняться файлы в папках с текущей датой
            if (!is_dir($dir)){//если такой папки нет
                mkdir($dir);//создадим
            }
            $file_name = uniqid() . '_' . $file->baseName . '.' . $file->extension;//уникальный код + имя файла и его расширение
            $this->img = $dir . $file_name;//в свойство img (БД) помещаем путь к файлу и его имя
            $file->saveAs($this->img);//сохраняем запись в БД
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
