<?php


namespace app\controllers;


use yii\web\Controller;

class AppController extends Controller//общий контроллер
{
    public function beforeAction($action)//срабатывает перед каждым action
    {
        $this->view->title = \Yii::$app->name;//определяем имя вкладки (из web)
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    protected function setMeta($title = null, $keywords = null, $description = null)//функция установки метаданных. НЕПОНЯТНО!!!
    {
        $this->view->title = $title;
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => "$keywords"]);
        $this->view->registerMetaTag(['name' => 'description', 'content' => "$description"]);
    }
}